default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: njmj
  password: password
  host: localhost

development:
  <<: *default
  database: njmj_development

test:
  <<: *default
  database: njmj_test

production:
  <<: *default
  database: njmj_production
